global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'consumer-service'
    static_configs:
      - targets: ['consumer-service:8001']

  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml_service:8080']

  - job_name: 'genai-service'
    static_configs:
      - targets: ['genai_service:8080']
