{
 "title": "System Health",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average API Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "api_request_latency_sec_sum / api_request_latency_sec_count",
     "legendFormat": "Avg API Latency"
    }
   ]
  },
  {
   "title": "ML Service Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ml_model_inference_sec_sum / ml_model_inference_sec_count",
     "legendFormat": "ML Inference Time"
    }
   ]
  },
  {
   "title": "Last LLM TTFT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llm_time_to_first_token_sec", "legendFormat": "LLM TTFT" }
   ]
  },
  {
   "title": "GenAI Service Latency (Explanation + RAG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "genai_explanation_latency_sec_sum / genai_explanation_latency_sec_count",
     "legendFormat": "Avg GenAI Latency"
    },
    {
     "expr": "genai_rag_retrieval_sec_sum / genai_rag_retrieval_sec_count",
     "legendFormat": "Avg RAG Latency"
    }
   ]
  },
  {
   "title": "Clinical Risk Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level) (severity_total)",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}